services:
  portfolio-db:
    image: pgvector/pgvector:pg17
    container_name: portfolio-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
      POSTGRES_DB: "portfolio"
    restart: always
    volumes:
      # Use this option to persist the PostgreSQL DBs in a shared volume.
      - ./postgresdata:/var/lib/postgresql/data:rw,delegated
      # Use this option to persist the PostgreSQL DBs in a data volume.
      # - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: portfolio-app
    build: .
    links:
      - portfolio-db
    depends_on:
      portfolio-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY="justasecretkey"
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=portfolio
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgrespassword
      - DATABASE_HOST=portfolio-db
      - DATABASE_PORT=5432
      - DEBUG=True
      - ALLOWED_HOSTS=*
